#use_frameworks!

target 'MHData_Example' do
  pod 'MHData', :path => '../'

  target 'MHData_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    File.open('Pods/Target Support Files/MHData/MHData-prefix.pch', 'a') { |f| f.puts("#define MHDATA_PREFIX_TO_ADD ZZ\n") }
end